```plantuml
@startuml Process_View
participant View as View <<Component>>
participant Component as Component <<Component>>
participant Model as Model <<Component>>
participant Service as Service <<Component>>
participant HTTPDriver as HTTPDriver <<Component>>
participant MastersData as BE <<Container (C4)>>

activate View
View -> Component: submit the form
activate Component
Component -> Model**: get the medical record number in route and data in form
Component -> Service: edit the patient information
activate Service
Service -> HTTPDriver: PATCH
activate HTTPDriver
HTTPDriver -> BE: PATCH (/api/patients/:medicalRecordNumber)
activate BE
BE -> BE: validates all information\nand edits patietn information
return response
return response
Service -> Model: transforms response data
activate Model
return patient
return patient
return success/fail message

@enduml
```