```plantuml
@startuml Process_View
participant PatientRoute as Route <<Route>>
participant PatientController as Controller <<Controller>>
participant EditingPatientDTO as DTO <<DTO>>
participant PatientService as Service <<Service>>
participant EmailService as EmailService <<Service>>
participant PatientRepository as Repository <<Repository>>
participant Patient as Domain <<Domain>>
participant PatientLogger as Logger <<Logger>>
participant PatientMapper as Mapper <<Mapper>>
[o-> Route: PATCH (/api/patients/{medicalRecordNumber})
activate Route
Route -> Controller : PATCH
activate Controller
Controller -> DTO** : recieves request body info
Controller -> Service : editPatient(medicalRecordNumber, editingPatientDTO)
activate Service
Service -> Repository : findByMedicalRecordNumber(medicalRecordNumber)
activate Repository
return patient
Service -> Domain : changeName(newName)
Service -> Domain : changeEmail(newEmail)
Service -> Domain : changePhoneNumber(newPhoneNumber)
Service -> Domain : changeMedicalConditions(newMedicalConditions)
Service -> Logger : logChanges(patient)
Service -> Repository : save(patient)
alt content editable contains sensitive info
    Service -> EmailService : sendEmail(email)
end
Service -> Mapper : toDTO(patient)
activate Mapper
return patientDTO
Service --> Controller : patientDTO
deactivate Service
Controller --> Route : response
deactivate Controller
<-- Route : response

@enduml
```