```plantuml
@startuml Process_View
participant View as View <<Component>>
participant Component as Component <<Component>>
participant Model as Model <<Component>>
participant Service as Service <<Component>>
participant HTTPDriver as HTTPDriver <<Component>>
participant MastersData as BE <<Container (C4)>>

activate View
View -> Component: submit the filter form
activate Component
Component -> Model**: get the data in filter form
Component -> Service: search for patients
activate Service
Service -> HTTPDriver: GET
activate HTTPDriver
HTTPDriver -> BE: GET (/api/patients/search)
activate BE
BE -> BE: search for patients\naccording to the filter
return response
return response
Service -> Model: transforms response data
activate Model
return patients
return patients
return patients/fail message

@enduml
```