```plantuml
@startuml Process_View
participant SPA as FE <<Container (C4)>>
participant "MastersData" as BE <<Container (C4)>>

activate FE
FE -> BE: DELETE (/api/user/patients/delete/{email})
activate BE
BE -> BE: receive request body info, validates \nand sends confirmation email
return response
deactivate BE
deactivate FE
FE -> BE: DELETE (/api/user/patients/delete/confirmation/{token})
activate FE
activate BE
BE -> BE : receive token, validates \nand deletes user and\nall associated data
return response
deactivate BE
@enduml
```