
```plantuml
@startuml Process_View
actor Admin 
participant System <<System>>

activate Admin

Admin -> System: Make a request to create a new patient profile
activate System
System --> Admin : Asks the necessary information
Admin -> System: Provides the necessary information
System --> Admin : Success/Error message
deactivate System
deactivate Admin

@enduml
```