```plantuml
@startuml Process_View
participant View as View <<Component>>
participant Component as Component <<Component>>
participant Model as Model <<Component>>
participant Service as Service <<Component>>
participant HTTPDriver as HTTPDriver <<Component>>
participant MastersData as BE <<Container (C4)>>

activate View
View -> Component: click in button to delete patient
activate Component
Component -> Model**: get the medical record number in route
Component -> Service: delete the patient
activate Service
Service -> HTTPDriver: DELETE
activate HTTPDriver
HTTPDriver -> BE: DELETE (/api/patients/:medicalRecordNumber)
activate BE
BE -> BE: validates all information\nand deletes patient
return response
return response
return response
return success/fail message

@enduml
```