```plantuml
@startuml Process_View_Prior_Confirmation
participant View as View <<Component>>
participant Component as Component <<Component>>
participant Model as Model <<Component>>
participant Service as Service <<Component>>
participant HTTPDriver as HTTPDriver <<Component>>
participant MastersData as BE <<Container (C4)>>

activate View
View -> Component: submit the form
activate Component
Component -> Model**: get the email in route and data in form
Component -> Service: edit the patient user information
activate Service
Service -> HTTPDriver: PATCH
activate HTTPDriver
HTTPDriver -> BE: PATCH (/api/users/patients/edit)
activate BE
BE -> BE: validates all information\nand edits new patient user,\nsending an confirmation email\nin case of editing sensitive data
return response
return response
return response
alt edits sensitive data
Component --> View : message to confirm the\nedition/fail message
end
return success/fail message
@enduml
```