```plantuml
@startuml Process_View_Posterior_Confirmation
participant View as View <<Component>>
participant Component as Component <<Component>>
participant Model as Model <<Component>>
participant Service as Service <<Component>>
participant HTTPDriver as HTTPDriver <<Component>>
participant MastersData as BE <<Container (C4)>>

activate View
View -> Component: redirect the confirmation page
activate Component
Component -> Model**: get the email, token and info to edit in route
Component -> Service: confirm the edit of the patient user
activate Service
Service -> HTTPDriver: PATCH
activate HTTPDriver
HTTPDriver -> BE: PATCH (/api/users/patients/edit/confirm)
activate BE
BE -> BE: validates all information\nand confirms the edition\nof patient user
return response
return response
Service -> Model: transforms response data
activate Model
return user
return user
return success/fail message

@enduml
```