
```plantuml
@startuml Process_View
participant "Back-end" as BE <<Container>>

[o-> BE: Create a new patient profile and inputs information\n(First Name, Last Name, Full Name, Date of Birth, Gender,\nEmail, Phone Number, Emergency Contact)
activate BE
<-- BE: Sucessfully created the new patient profile
deactivate BE
@enduml
```