
```plantuml
@startuml Process_View
participant "Back-end" as BE <<Container>>

[o-> BE: POST (/api/patients)
activate BE
BE -> BE: receive request body info,\ncreates patient profile\nand saves in DB
<-- BE: response
deactivate BE
@enduml
```