```plantuml
@startuml Process_View_Prior_Confirmation
participant SPA as FE <<Container (C4)>>
participant Route as Route <<Route>>
participant Controller as Controller <<Controller>>
participant DTO as DTO <<DTO>>
participant ConfirmationDTO as ConfirmationDTO <<DTO>>
participant Service as Service <<Service>>
participant EmailService as EmailService <<Service>>
participant Repository as Repository <<Repository>>
participant PatientRepository as PatientRepository <<Repository>>
activate FE
FE-> Route: DELETE (/api/users/patients/delete)
activate Route
Route -> Controller : DELETE
activate Controller
Controller -> DTO** : recieves request body info
Controller -> Service : deletes the user and associated patient data
activate Service
Service -> Repository : find user by email
activate Repository
return user
Service -> PatientRepository : find patient by email
activate PatientRepository
return patient
Service -> EmailService : sends email with the confirmation token
Service -> ConfirmationDTO** : creates the DTO with confirmation token and email
return DTO
return response
return response
@enduml
```