```plantuml
@startuml Process_View_Prior_Confirmation
participant View as View <<Component>>
participant Component as Component <<Component>>
participant Model as Model <<Component>>
participant Service as Service <<Component>>
participant HTTPDriver as HTTPDriver <<Component>>
participant MastersData as BE <<Container (C4)>>

activate View
View -> Component: click in button to delete patient user
activate Component
Component -> Model**: get the email in route
Component -> Service: delete the patient user
activate Service
Service -> HTTPDriver: DELETE
activate HTTPDriver
HTTPDriver -> BE: DELETE (/api/users/patients/delete/confirm)
activate BE
BE -> BE: validates all information,\nand sends an confirmation email\nof deletion to the patient user
return response
return response
return response
return success/fail message
@enduml
```