```plantuml
@startuml Process_View_Posterior_Confirmation
participant View as View <<Component>>
participant Component as Component <<Component>>
participant Model as Model <<Component>>
participant Service as Service <<Component>>
participant HTTPDriver as HTTPDriver <<Component>>
participant MastersData as BE <<Container (C4)>>

activate View
View -> Component: redirect the confirmation page
activate Component
Component -> Model**: get the email and token in route
Component -> Service: confirm the deletion of the patient user
activate Service
Service -> HTTPDriver: DELETE
activate HTTPDriver
HTTPDriver -> BE: DELETE (/api/users/patients/delete/confirm)
activate BE
BE -> BE: validates all information\nand confirms the deletion\nof patient user
return response
return response
return response
return success/fail message

@enduml
```