```plantuml
@startuml Process_View
participant PatientRoute as Route <<Route>>
participant PatientController as Controller <<Controller>>
participant DeletePatientConfirmationDTO as DTO <<DTO>>
participant PatientService as Service <<Service>>
participant PatientRepository as Repository <<Repository>>
participant PatientLoggeerRepository as LoggerRepository <<Repository>>
participant PatientLogger as Logger <<Logger>>
[o-> Route: DELETE (/api/patients/{medicalRecordNumber})
activate Route
Route -> Controller : DELETE
activate Controller
Controller -> DTO** : recieves request body info
Controller -> Service : deletePatient(medicalRecordNumber, deletePatientConfirmationDTO)
activate Service
Service -> Repository : findByMedicalRecordNumber(medicalRecordNumber)
activate Repository
return patient
Service -> Repository : delete(patient)
Service -> Logger : logChanges(patient)
alt the period mandated of data retention has expired
    Service -> Logger : createImportantLog(medicalRecordNumber, modificationDate)
    Service -> LoggerRepository: findLogsByPatientId(id)
    activate LoggerRepository
    return logs
    loop through logs
        Service -> LoggerRepository: delete(logs)
    end
end
deactivate Repository
deactivate Service
Controller --> Route : response
deactivate Controller
<-- Route : response

@enduml
```