```plantuml
@startuml Process_View
participant Route as Route <<Route>>
participant Controller as Controller <<Controller>>
participant DTO as DTO <<DTO>>
participant Service as Service <<Service>>
participant Repository as Repository <<Repository>>
[o-> Route: DELETE (/api/patients/{medicalRecordNumber})
activate Route
Route -> Controller : DELETE
activate Controller
Controller -> DTO** : recieves request body info
Controller -> Service : deletes the patient profile
activate Service
Service -> Repository : find patient by his medical record number
activate Repository
return patient
Service -> Repository : removes the patient from database
Service -> Service : logs the deletion
activate Service
deactivate Service
return response
return response
deactivate Controller
<-- Route : response

@enduml
```