```plantuml
@startuml Process_View
participant "SPA" as FE <<Container (C4)>>
participant "MastersData" as BE <<Container (C4)>>

activate FE
FE -> BE: GET (/api/patients/search)
activate BE
BE -> BE: receive request body info,\n and search for patient(s)
return response with list of patients
deactivate BE
deactivate FE
@enduml
```