```plantuml
@startuml Process_View_Posterior_Confirmation
participant UserRoute as Route <<Route>>
participant UserController as Controller <<Controller>>
participant ConfirmationRegisterPatientDTO as ConfirmationDTO <<DTO>>
participant UserService as Service <<Service>>
participant UserRepository as Repository <<Repository>>
participant PatientRepository as PatientRepository <<Repository>> 
participant Patient as Patient <<Domain>>
participant PatientMapper as Mapper <<Mapper>>
[o-> Route : POST(/api/users/patients/confirmation/{token})
activate Route
Route -> Controller : POST
activate Controller
Controller -> ConfirmationDTO** : recieves request body info
Controller -> Service : confirmPatientRegistration(confirmationRegisterPatientDTO)
activate Service
Service -> Service : validateToken(token)
activate Service
return flag
Service -> Repository : findUserByEmail(email)
activate Repository
return user 
Service -> PatientRepository : findPatientByEmail(email)
activate PatientRepository
return patient
Service -> Patient : associateUser(user)
Service -> Repository : save(user)
Service -> PatientRepository : save(patient)
Service -> Mapper : toDTO(patient)
activate Mapper
return patientDTO
Service --> Controller : patientDTO
deactivate Service
Controller --> Route : response
deactivate Controller
<-- Route : response
@enduml
```