```plantuml
@startuml Process_View_Posterior_Confirmation
participant Route as Route <<Route>>
participant Controller as Controller <<Controller>>
participant ConfirmationDTO as ConfirmationDTO <<DTO>>
participant Service as Service <<Service>>
participant Repository as Repository <<Repository>>
participant PatientRepository as PatientRepository <<Repository>>
 
[o-> Route : DELETE (/api/users/patients/delete/confirmation/{token})
activate Route
Route -> Controller : DELETE
activate Controller
Controller -> ConfirmationDTO** : recieves request body info
Controller -> Service : confirms the patient user and profile deletion
activate Service
Service -> Repository : find user by email
activate Repository
return user
Service -> Service : validate token
activate Service
return flag
Service -> PatientRepository : find patient by email
activate PatientRepository
return patient
Service -> Repository : removes user from DB
Service -> PatientRepository : removes patient from DB
Service -> Service: log changes
activate Service
deactivate Service
return response
return response
@enduml
```