version: '3.8'

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: test
    volumes:
      - .:/usr/src/app
    ports:
      - "2226:2226"
    command: npm start
    depends_on:
      - db

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"