```plantuml
@startuml Process_View
participant PatientRoute as Route <<Route>>
participant PatientController as Controller <<Controller>>
participant CreatingPatientDTO as DTO <<DTO>>
participant PatientService as Service <<Service>>
participant PatientRepository as Repository <<Repository>>
participant Patient as Domain <<Domain>>
participant PatientMapper as Mapper <<Mapper>>
[o-> Route: POST (/api/patients)
activate Route
Route -> Controller : POST
activate Controller
Controller -> DTO** : recieves request body info
Controller -> Service : createPatient(creatingPatientDTO)
activate Service
Service -> Domain** : create(createPatientDTO)
Service -> Repository : save(patient)
Service -> Mapper : toDTO(patient)
activate Mapper
return patientDTO
Service --> Controller : patientDTO
deactivate Service
Controller --> Route : response
deactivate Controller
<-- Route : response

@enduml
```