
```plantuml
@startuml Process_View
actor Doctor
participant System <<System (C4)>>

activate Doctor

Doctor -> System: Make a request to search for entries in medical records
activate System
System --> Doctor: Displays all patients
Doctor -> System: Select a patient
System --> Doctor : Displays the tables for medical condition and allergies
Doctor -> System: Writes the medical condition or selects the allergyw
System --> Doctor: Success/Error message
deactivate System
deactivate Doctor

@enduml
```