@startuml Process_View
actor Admin 
participant UI  as UI
participant Backend as backend

activate Admin

Admin -> UI: Request to list Operation Types
activate UI
note over UI, backend : US 5.1.23
UI --> Admin: Display list of Operation Types

Admin -> UI: Select an Operation Type to disable
UI -> Admin: Show confirmation prompt
Admin -> UI: Confirm disable operation type
UI -> backend: HTTP POST request to disable operation type
activate backend
backend -> backend: Disable operation type in DB
backend --> UI: Return success/error message
deactivate backend
UI --> Admin: Display success/error message
deactivate UI
deactivate Admin

@enduml
