
```plantuml
@startuml Process_View
participant "SPA" as FE <<Container (C4)>>
participant "MastersData2" as BE2 <<Container (C4)>>

activate FE
FE -> BE2: PUT (/api/medicalConditions/:name)
activate BE2
BE2 -> BE2: receive request body info,\nupdate medical condition
return response
@enduml
```