```plantuml
@startuml Process_View
participant "MastersData" as BE <<Container (C4)>>

[o-> BE: PATCH (/api/user/patients/{logToken}/edit)
activate BE
BE -> BE: receive request body info, validates, \nedits user info
<-- BE: response
deactivate BE
alt information contains sensitive data
[o-> BE: PATCH (/api/user/patients/{logToken}/edit/confirmation/{token})
activate BE
BE -> BE : receive token and \nsensitive data to edit, \nedits sensitive data info
<-- BE: response
deactivate BE
end
@enduml
```