```plantuml
@startuml Process_View
participant SPA as SPA <<Container (C4)>>
participant Route as Route <<Route>>
participant Controller as Controller <<Controller>>
participant DTO as DTO <<DTO>>
participant Service as Service <<Service>>
participant Repository as Repository <<Repository>>
participant Mapper as Mapper <<Domain Service>>
participant Domain as Domain <<Domain>>
activate SPA
SPA -> Route: POST (/api/roomTypes)
activate Route
Route -> Controller : POST
activate Controller
Controller -> DTO** : recieves request body info
Controller -> Service : add new room type
activate Service
Service -> Service : validate if designation is unique
activate Service
return validation
Service -> Domain** : creates the entity
Service -> Repository : saves in Database
Service -> Mapper : entity to DTO
activate Mapper
return DTO
return DTO
return response
return response

@enduml
```