name: .NET CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore MastersData
      - name: Build
        run: dotnet build --no-restore MastersData
      - name: Test
        run: dotnet test --no-build --verbosity normal MastersData
      - name: Publish Build Artifacts
        run: dotnet publish MastersData -c Release -o ./output
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: MastersData-Build
          path: ./MastersData/output

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: MastersData-Build

      - name: Deploy to MD2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: vsgate-ssh.dei.isep.ipp.pt
          port: 10422
          username: root
          password: "your_root_password_here"
          script: |
            echo "Making the script executable..."
            chmod +x /root/run_spa.sh
            echo "Executing the deployment script..."
            /root/run_spa.sh
