name: .NET CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore MastersData
      - name: Build
        run: dotnet build --no-restore MastersData
      - name: Test
        run: dotnet test --no-build --verbosity normal MastersData
      - name: Publish Build Artifacts
        run: dotnet publish MastersData -c Release -o ./output
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: MastersData-Build
          path: ./MastersData/output
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          mkdir build
          echo "Some build output" > build/output.txt
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: MastersData2-Build
          path: build/output.txt

          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      
      - name: Deploy  MD2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: vsgate-ssh.dei.isep.ipp.pt
          port: 10373
          username: root
          password: "password"
          script: |
            echo "Making the script executable..."
            chmod +x /root/update_app.sh
            echo "Executing the deployment script..."
            /root/update_app.sh
      
      - name: Deploy  MD1
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: vsgate-ssh.dei.isep.ipp.pt
          port: 10584
          username: root
          password: "mXef8xNlrclX/QGjNdP5"
          script: |
            echo "Making the script executable..."
            chmod +x /root/update-dotnet.sh
            echo "Executing the deployment script..."
            /root/update-dotnet.sh

      - name: Deploy Frontend
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: vsgate-ssh.dei.isep.ipp.pt
          port: 10422
          username: root
          password: "8NPiYjXz4N1VUxwuMgyP"
          script: |
            echo "Making the script executable..."
            chmod +x /root/run_spa.sh
            echo "Executing the deployment script..."
            /root/run_spa.sh

