```plantuml
@startuml Process_View
participant "SPA" as FE <<Container (C4)>>
participant "MastersData" as BE <<Container (C4)>>

activate FE
FE -> BE: DELETE (/api/patients/{medicalRecordNumber})
activate BE
BE -> BE: receive request body info,\n and deletes patient profile
return response
@enduml
```