```plantuml
@startuml Process_View_Prior_Confirmation
participant View as View <<Component>>
participant Component as Component <<Component>>
participant Model as Model <<Component>>
participant Service as Service <<Component>>
participant HTTPDriver as HTTPDriver <<Component>>
participant MastersData as BE <<Container (C4)>>

activate View
View -> Component: submit the form
activate Component
Component -> Model**: get the data in form
Component -> Service: register the new patient user
activate Service
Service -> HTTPDriver: POST
activate HTTPDriver
HTTPDriver -> BE: POST (/api/users/patients)
activate BE
BE -> BE: validates all information\nand registers the new patient user,\nsending an confirmation email
return response
return response
return response
return message to confirm the\naccount/fail message

@enduml
```