```plantuml
@startuml Process_View_Posterior_Confirmation
participant View as View <<Component>>
participant Component as Component <<Component>>
participant Model as Model <<Component>>
participant Service as Service <<Component>>
participant HTTPDriver as HTTPDriver <<Component>>
participant MastersData as BE <<Container (C4)>>

activate View
View -> Component: redirect the confirmation page
activate Component
Component -> Model**: get the email and token in route
Component -> Service: confirm the registration of the new patient user
activate Service
Service -> HTTPDriver: POST
activate HTTPDriver
HTTPDriver -> BE: POST (/api/users/patients/confirm)
activate BE
BE -> BE: validates all information\nand confirms the registration\nof the new patient user
return response
return response
Service -> Model: transforms response data
activate Model
return user
return user
return success/fail message

@enduml
```